apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: project
spec:
  selector:
    app: nginx
    version: v1
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: project
  labels:
    app: nginx
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
