apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: payment
    newName: weaveworksdemos/payment
    newTag: 0.4.3

patches:
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: payment

patchesStrategicMerge:
  - patch-deployment.yaml
