apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: frontend
    newName: weaveworksdemos/front-end
    newTag: 0.3.12

patches:
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: front-end

patchesStrategicMerge:
  - patch-deployment.yaml
