apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: elasticsearch-gateway
  namespace: devops
spec:
  selector:
    istio: devops-ingressgateway
  servers:
    - hosts:
        - { { YOUR DOMAIN } } # change your domain
      port:
        name: http
        protocol: HTTP
        number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch-virtualservice
  namespace: devops
spec:
  hosts:
    - { { YOUR DOMAIN } } # change your domain
  gateways:
    - elasticsearch-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: eck-elasticsearch-es-http
            port:
              number: 9200
