apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: user-db
    newName: weaveworksdemos/user-db
    newTag: 0.3.0

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-service.yaml
