---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
    - name: tcp-catalogue-db
      port: 3306
      targetPort: 3306
