apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: carts
    newName: weaveworksdemos/carts
    newTag: 0.4.8

patches:
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: carts

patchesStrategicMerge:
  - patch-deployment.yaml
