apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: sock-shop
spec:
  template:
    metadata:
      annotations:
        # Istio sidecar proxy .resources.requests
        sidecar.istio.io/proxyCPU: "100m"
        sidecar.istio.io/proxyMemory: "128Mi"

        # Istio sidecar proxy .resources.limits
        sidecar.istio.io/proxyCPULimit: "200m"
        sidecar.istio.io/proxyMemoryLimit: "256Mi"
    spec:
      containers:
        - name: carts
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      # nodeSelector:
      #   kubernetes.io/os: linux
      #   $patch: replace
