apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: {{ .Values.namespace.project }}
spec:
  storageClassName: redis
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
  accessModes:
    - ReadWriteOnce