apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace.project }}
  labels:
    app: redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: redis
  ports:
  {{- range .Values.redis.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end}}