apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis
  namespace: {{ .Values.namespace.project }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true