redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  service:
    type: NodePort

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
