apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: session-db
    newName: redis
    newTag: alpine

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-service.yaml
