apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck-kibana
  namespace: monitoring
spec:
  version: 8.0.0
  count: 1
  elasticsearchRef:
    name: eck-elasticsearch
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
