apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: user
    newName: weaveworksdemos/user
    newTag: 0.4.7

patches:
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: user

patchesStrategicMerge:
  - patch-deployment.yaml
