apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: rabbitmq
    newName: rabbitmq
    newTag: 3.6.8-management

patches:
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: rabbitmq

patchesStrategicMerge:
  - patch-deployment.yaml
