apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: sock-shop
spec:
  ports:
    - name: tcp-rabbitmq
      port: 5672
      targetPort: 5672
    - name: tcp-exporter
      protocol: TCP
      port: 9090
      targetPort: exporter
