apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: { { changeme1 } }
  namespace: { { changeme2 } }
data:
  .dockerconfigjson: { { base64 encoded data } }
---
## Case 1. Harbor
## $ kubectl create secret docker-registry {{ changeme1 }} \
##   -n {{ changeme2 }}
##   --docker-server={{ harbor.server }} \
##   --docker-username={{ harbor.username }} \
##   --docker-password={{ harbor.password }}
