apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kibana-gateway
  namespace: monitoring
spec:
  selector:
    istio: devops-ingressgateway
  servers:
    - hosts:
        - <kibana host> # need to change
      port:
        name: http
        protocol: HTTP
        number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-virtualservice
  namespace: monitoring
spec:
  hosts:
    - <kibana host> # need to change
  gateways:
    - kibana-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: eck-kibana-kb-http
            port:
              number: 5601
