apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: carts-db
    newName: mongo
    newTag: latest

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-service.yaml
