---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
    - name: tcp-carts-db
      port: 27017
      targetPort: 27017
