apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workspace

images:
  - name: catalogue
    newName: weaveworksdemos/catalogue
    newTag: 0.3.5

patches:
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: catalogue

patchesStrategicMerge:
  - patch-deployment.yaml
